sudo: required
language: go
services:
- docker
go:
- go1.11rc1
env:
- GO111MODULE=on
install:
- set -e
- go mod vendor
script:
- test -z "$(bin/format | tee >(cat >&2))"
- bin/test -nodes=2 -compilers=2
